### ISSUE TITLE
Allow changing container command within the wizard

### ISSUE THREAD

**Issue by yann-eugone** [ledup/maildev#1]
When it is required to run the service using TLS, we need to change the service command.

For automation purpose, it could be really nice if that command was allowed to be set from the outsite :

```
led service add --image=maildev --service=maildev --default --options="COMMAND=node bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS"
```

I believe we will be required to update `maildev.var.yml` with something like

```diff
vars:
  - PORT
+  - COMMAND
data:
  PORT:
    title: Port required
    default: 1080
    type: integer
+  COMMAND:
+    title: Command to run when container starts
+    default: "..."
+    type: string
```

And `maildev.tpl.yml` with something like

```diff
    image: ledup/maildev
+    command: {{COMMAND}}
    ports:
      - "{{PORT}}:80"
```

Are you interested in a PR for this ?

**Comment by bonidier** [comment]
Hi,
I've just updated our image to natively disable STARTTLS + bumped maildev to 1.1.0 instead of 1.1.0~rc3

nothing to change from Compose file, just refresh the image
